Add stein plane and vehicle
TacticalTrainingTeam/ttt_a3 pull request #72
Opened 2024-11-04 22:30 UTC by Andx667

2025-01-04 18:22 UTC, Andx667 commented on addons/stein_medic_vehicle/functions/fnc_addActions.sqf
> +
Funktionsheader ergänzen wie bei den anderen Funktionen

2025-01-04 18:22 UTC, Andx667 commented on addons/stein_medic_backpack/initSettings.inc.sqf
> +    true,
default wert auf false setzen

2025-01-04 18:22 UTC, Andx667 commented on addons/stein_medic_backpack/config.cpp
> +        requiredAddons[] = {"ttt_main"};
required addons ergänzen

2025-01-05 08:59 UTC, MenomDE requested changes

2025-01-05 08:59 UTC, MenomDE commented on addons/medic_vehicle/stringtable.xml
Stein Medzinische Einrichtung zu
TTT medizinische Einrichtung

Usw.

Gleich der Korrekturen in der Stringtable des Backpacks übernehmen. Irgendwie konnte ich am Handy die Datei nicht bearbeiten fürs Fahrzeug.

2025-01-05 10:52 UTC, MenomDE approved these changes

2025-01-05 10:52 UTC, merged